spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laptopKG
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: specterplay2@gmail.com
    password: thplixdghwlfqbis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwtSecret: 576D5A7133743677397A24432646294A404E635266556A586E32723575377821
  jwtExpirationInMs: 36000000
  refreshExpirationInMs: 604800000